### PR TITLE
Make CMD use an absolute path for run.sh

### PR DESCRIPTION
**Pull request by tmckayus**

### CODE REVIEW

**Comment by tmckayus** [comment]
@elmiko @willb ptal

**Comment by elmiko** [comment]
thanks Trevor, i will give this a test

**Comment by willb** [comment]
@tmckayus can you amend the commit to have attribution?

**Comment by tmckayus** [comment]
@willb oops done

**Comment by willb** [comment]
LGTM.  Thanks, Trev!

**Comment by elmiko** [comment]
i tried this out and am getting an error

**steps to reproduce**

1. create a new project
1. install ophicleide template `oc create -f https://radanalytics.io/assets/ophicleide/ophicleide-setup-list.yaml`
1. edit build config to point at `https://github.com/tmckayus/ophicleide-training` and the `abspath` branch
1. run builds
1. setup mongodb
1. run deployments

**results**
ophicleide pod ends up in a crash back-off loop. i see this error in the ophicleide-training pod

```
/entrypoint: line 74: /bin/sh -c /opt/ophicleide/run.sh: No such file or directory
```

it looks like the file is there, so i'm not sure what is going on

```
sh-4.2$ ls /opt/ophicleide/
Dockerfile     app.py       requirements-tests.txt  tox.ini
Dockerfile-ci  bin          requirements.txt        wheel-requirements.txt
LICENSE        conf.py      run.sh                  worker.py
README.md      controllers  swagger
__init__.py    pymongo.zip  tests
```

**Comment by willb** [comment]
There’s no shebang — we need one or an explicit entrypoint, I think

**Comment by tmckayus** [comment]
@elmiko did you run this with an updated openshift-spark as the base image? This happens because the /entrypoint has quotes around $CMD and causes bash to treat "/bin/sh -c /opt/ophicleide/run.sh" as a single word

**Comment by tmckayus** [comment]
https://github.com/radanalyticsio/openshift-spark/pull/81 for master
https://github.com/radanalyticsio/openshift-spark/pull/82 for 2.3

**Comment by elmiko** [comment]
ahh, ok. i missed that i needed the updated images. i will try again.

**Review by elmiko — APPROVED** [review]
ok, after testing with the new image everything worked well.

should we merge this now or wait for the upstream image update?

**Comment by tmckayus** [comment]
I think we can merge now, the absolute path can't hurt anything even in the old image (or at least I don't see how it could :) )

**Comment by elmiko** [comment]
ack, thanks Trevor!

**Pull request merged**
