### PR TITLE
Handle error case when query term isn't in the vocabulary

### LINKED ISSUE #9: querying a non-existent word returns a 500
when querying a word that does not exist in the source material, the server will return a 500 error. i would expect that it might return an empty list or something in these cases, or perhaps we should return a more standard error.

steps to reproduce:
1. create a model based off the works of jane austen (https://www.gutenberg.org/cache/epub/31100/pg31100.txt)
2. create a query for the word "bob"

results:

```
HTTP/1.0 500 INTERNAL SERVER ERROR
Content-Length: 252
Content-Type: application/problem+json
Date: Wed, 28 Sep 2016 19:06:29 GMT
Server: Werkzeug/0.11.11 Python/3.5.1

{
    "detail": "The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.",
    "status": 500,
    "title": "Internal Server Error",
    "type": "about:blank"
}
```

### PR DESCRIPTION
**Pull request by willb**
Closes #9

### CODE REVIEW

**Comment by willb** [comment]
@elmiko ptal

**Comment by elmiko** [comment]
i think this is fine, my only nit is that we should start to move towards standardizing the error responses based on the schema.

so, something along the lines of:

```
{
  "errors": [
    {
      "title": "Bad Request",
      "status": 400,
      "details": "Foo isn't even in my vocabulary!"
    }
  ]
}
```

**Comment by elmiko** [comment]
lgtm, thanks Will!

**Review by elmiko — APPROVED** [review]

**Comment by willb** [comment]
Thanks for the review, Mike!

**Pull request merged**
